notifications:
    email:
        on_success: never
        on_failure: always
language: node_js
addons:
    apt:
        update: true
env:
    global:
        - GH_USER=Twiddly
        - GH_MAIL=pew@pewpew.moe
        - REPO=happypandax/desktop
        - DEPLOY_REPO=happypandax/desktop
        - secure: vCKcIOnhT0j057+SIDaYdGzymoDBc7Gl395mDLiETcdi4E4FsHNUx+bCa8gT3eeB70sQWTRSZJEbyQIkWejA53rx4dlum5e68CgOUbYx9aAl4vK/PKCL2SYxzJTqEgvqL4a3zkIdjjrHriIAix3UXl6ZbjQGKE6atI6NewKh1p+eEN8sExQ6+WMNzmwQg2Or07COK/nTaGTay0UAaZ+iX2H+ljspNvFbxLUkb+o/x0UILcmVnCerqGQZ1D8pKMy4e6JIv6Zco9m8Oqhen9/+vDZDOalXFOx5Ctf/1QEnZIbyNOQqpvb8s84g0swn5QUwcGNYQ7YNTHU/1jc/qQwy+DR/131O3jGvs/GUoMiZ3wWhkheRqqR/nhy+j340F53EUuiJSsX0KMvjOfdeT3D+gkmfr9omPK/KSwsbxMiTQ3UhjYtEat4Fp3Eq6e3nB8C1+Bbu85cQOyb31cWA5jc7z2wX2UkRZrnPqv0dnVFrRBfaJx2pUAtpCy1Skz2xlwqFwB7/uSXDEUuNvI/6gDcuNWLgDE9Zj4U8P3O+rucyO5M5Z+G8yNsFES1+7fQE52x2vL0lwL+3VJL7OnKyuqDLIG6nXmIsffk7VXV/Ccngux5Y8DsVF2gRJwIlN99mnv5pv81awBXytj0ip5UubLULQykolc2c9Kq8PNWHCIZ2U6w=
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
        - os: osx
          language: generic

cache:
    directories:
        - node_modules

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nvm install 8; fi
    - node --version
    - npm update -g npm

install:
    - npm install

before_deploy:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist-linux; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist-osx; fi

    - export APP_VERSION=$(node -pe "require('./package.json').version")
    - export APP_RELEASE_NAME="HappyPanda X Desktop v$APP_VERSION"
    - export VERSION_TAG=v$APP_VERSION

    - CWD=$(pwd)
    - git clone https://github.com/$DEPLOY_REPO.git ../_travis_deploy_repo
    - cd ../_travis_deploy_repo
    - git config --local user.name "$GH_USER"
    - git config --local user.email "$GH_MAIL"
    - git tag -a $VERSION_TAG -m "$APP_RELEASE_NAME" || echo "Tag already exists, skipping"
    - git push --quiet "https://$GITHUB_TOKEN@github.com/$DEPLOY_REPO.git" $VERSION_TAG > /dev/null 2>&1 || echo  "Tag already exists, skipping"
    - echo $APP_RELEASE_NAME
    - cd $CWD

    - git config --local user.name "$GH_USER"
    - git config --local user.email "$GH_MAIL"
    - git tag -a $VERSION_TAG -m "$APP_RELEASE_NAME" || echo "Tag already exists, skipping"

    - ls -l -R dist

deploy:
    provider: releases
    overwrite: true
    skip_cleanup: true
    tag_name: $VERSION_TAG
    name: $APP_RELEASE_NAME
    file_glob: true
    file: dist/*
    draft: true
    target_commitish: master
    api_key: $GITHUB_TOKEN
    repo: $DEPLOY_REPO
    on:
        branch: master
