notifications:
    email:
        on_success: never
        on_failure: always
language: node_js
addons:
    apt:
        update: true
env:
    global:
        - GH_USER=Twiddly
        - GH_MAIL=pew@pewpew.moe
        - REPO=happypandax/desktop
        - DEPLOY_REPO=happypandax/desktop
        - secure: "J8Yy4o3sozjtoBe8jKvBiBjOGpmvnCgU3tVlpp/PnHC9+5HfBiCeRJ7dsHGehInC3WLPNA30Uo3jontr0O1DWkBTtsTxNJO2/a8sqO3B0sTQHB+yLg7B1tD4wxkgZKDQ30Am7gbNxAiNz1PeHEgsLcDH8v/Z1js+3+/j8/veaDYKuO8UjVB5krBPNc68KDZu/eBbxMiSMuS0N5qR2vEJksriXPxL6KRixRLYCWLe6NT8dES0vjDPYCheaiIG2j9uzZeYGf8LQfwFTNeZMJZf+0jEvDDNvjbKBlF+mvQhgo4131BYVbzraWDEV1zlWTn4qU7mqKz4XRCYHlalruyrmdixineLlCDSqjDpv0L8GN1bqbPgvPll53Luo5ZmL/kZWLYSbm3jRtYbdDW5S9T8vDxcDJVnttizPCBcFhNYwxPswUUENJVMTp9bAuRv4lh+TXiE18dMyRU0oMeXgTfRyaEXVGr0m5pD7Q84rUkgWbEKWPGMFaaP54qS91uu/EG6eWJSn+W/0juiXifiN4sQ01RS35BTuEXBCfT0jtEfh9xzn7rB9q6X22ZFtxBt8XsoYEG5m9uvKuYRcUXhTelAxWAbqgISwyhIpPsp3aZrhxD5Pb9j+vUpmCJI9GRCxRknT+QsQTFuTR69b4K/OU3xvFHP18dpY9IKonsf4vgmQW4="
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
        - os: osx
          language: generic

cache:
    directories:
        - node_modules

before_install:
    - nvm install 8
    - node --version
    - npm update -g npm

install:
    - npm install

before_deploy:
    - npm run dist-ci

    - export APP_VERSION=$(node -pe "require('./package.json').version")
    - export APP_RELEASE_NAME="HappyPanda X Desktop v$APP_VERSION"
    - export VERSION_TAG=v$APP_VERSION

    - CWD=$(pwd)
    - git clone https://github.com/$DEPLOY_REPO.git ../_travis_deploy_repo
    - cd ../_travis_deploy_repo
    - git config --local user.name "$GH_USER"
    - git config --local user.email "$GH_MAIL"
    - git tag -a $VERSION_TAG -m "$APP_RELEASE_NAME" || echo "Tag already exists, skipping"
    - git push --quiet "https://$GH_TOKEN@github.com/$DEPLOY_REPO.git" $VERSION_TAG > /dev/null 2>&1 || echo  "Tag already exists, skipping"
    - echo $APP_RELEASE_NAME
    - cd $CWD

    - git config --local user.name "$GH_USER"
    - git config --local user.email "$GH_MAIL"
    - git tag -a $VERSION_TAG -m "$APP_RELEASE_NAME" || echo "Tag already exists, skipping"

    - ls -l -R dist

deploy:
    provider: releases
    overwrite: true
    skip_cleanup: true
    tag_name: $VERSION_TAG
    name: $APP_RELEASE_NAME
    file_glob: true
    file: dist/*
    draft: true
    target_commitish: master
    api_key: $GH_TOKEN
    repo: $DEPLOY_REPO
    on:
        branch: master
